language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
install:
 # install Python dependencies
 - pip install --upgrade pip
 - pip -V
 - "pip install -e .[tests,markup]"
 - pip install python-coveralls
 # install Node 6
 - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6
 - node -v
 # install Node dependencies
 - npm install -g npm
 - npm -v
 - npm install
 - npm run build
 # Java 8 for html5validator
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle

script:
 - flake8
 - npm run lint
 - localcrawl --start http://localhost:5000 --run databench --log DEBUG
 - html5validator --root _crawled/
 - nosetests -vv --with-coverage --cover-erase --cover-inclusive
after_success:
 - coveralls || true
